version: 2
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.revision={{.Commit}} -X main.built={{.Date}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    goarm:
      - '6'
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: 'arm'
      - goos: windows
        goarch: 'arm'
    binary: '{{ .ProjectName }}'
    main: .
archives:
  - formats: [ binary ]
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
checksum:
  algorithm: sha256
winget:
  - name: watch
    publisher: echocat
    short_description: "Like the unix one but works cross-platform without magic. 😄"
    privacy_url: https://echocat.org
    license: MIT
    package_identifier: echocat.watch
    commit_author:
      name: echocat-bot
      email: 16277609+echocatbot@users.noreply.github.com
    commit_msg_template: 'chore: release {{.PackageIdentifier}} {{.Tag}}'
    release_notes_url: https://github.com/echocat/watch/releases/tag/{{.Tag}}
    repository:
      owner: echocat
      name: winget-pkgs
      branch: 'chore/watch-{{.Version}}'
      pull_request:
        enabled: true
        draft: false
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master
