builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.revision={{.Commit}} -X main.built={{.Date}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: '{{ .ProjectName }}'
archives:
  - format: binary
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
checksum:
  algorithm: sha256